#!/bin/bash

# This is the install script for Get-Pak, feel free to analize.
# This will install Get-Pak to $PREFIX/bin/getpm (Or /bin/getpm)

clear

echo "Welcome to Get-Pak!"
echo "This script will auto-install all the things you need."
echo "If you are using Linux, please run this as root."

curl --silent https://raw.githubusercontent.com/SCOS-Apps/get-pak/refs/heads/master/getpm | tee $PREFIX/bin/getpm > /dev/null
chmod +rwx $PREFIX/bin/getpm
echo "[✓] Done!"
