#!/bin/bash

# This is the install script for Get-Pak, feel free to analize.
# This will install Get-Pak to ~/.var/app/scos.scos-apps.Get-Pak/

circle_texture="| \ - / |"

clear

echo "Welcome to Get-Pak!"
echo "This script will auto-install all the things you need."
echo

if [ -z "${HOME}" -o "${HOME}" == "/" -o "${HOME}" == "/root*" ]; then
	echo "[E] Please set home dir to something else!" 1>&2
	exit 1
fi

mkdir ~/.var
mkdir ~/.var/app
mkdir ~/.var/app/scos.scos-apps.Get-Pak

curl --silent https://raw.githubusercontent.com/SCOS-Apps/get-pak/refs/heads/master/getpm | tee ~/.var/app/scos.scos-apps.Get-Pak/getpm > /dev/null
chmod +x $HOME/.var/app/scos.scos-apps.Get-Pak/getpm
echo 'export PATH=$PATH:$HOME/.var/app/scos.scos-apps.Get-Pak' | tee -a ~/.bashrc > /dev/null
source ~/.bashrc
echo "[✓] Done!"
